### ISSUE TITLE
nice to have:would be cool to see just one of them:entries, followers or following when I click on user, not all of them cuz when there are too many it gonna stuck  

### ISSUE THREAD

**Issue by dirmansebastian** [AkashaProject/dapp#100]
also, these buttons(marked with red) must work to enable/disable, just to see what i want to see
![enable_disable](https://user-images.githubusercontent.com/15945292/34696205-8cda3c8e-f4d6-11e7-92c1-3d550fc67e80.JPG)

**Comment by bogdanbrezuica** [comment]
Hello @sebastianrs95 . Entries and profiles are lazy loading, so it shouldn't stuck even if you have a lot of entries/followers. The logic is similar to the dashboard columns, where you can try adding 10-15 columns and still work ok (just an increase in RAM usage that we will look into optimizing later)

About the profile page, we will probably add even more relevant columns in the future, like a user's comments/votes/lists etc.

What do you think?

**Comment by Kuurusch** [comment]
@akashaTeam I think it would be necessary to make it ajustable in the settings, if other can see my followers, and more importent whom I follow!

**Comment by bogdanbrezuica** [comment]
For the moment, we will stick with the current design for this. Followers/following are public, like on Twitter. Thanks for the suggestions!

PS: Feel free to re-open this issue if you have other arguments for this
