### ISSUE TITLE
IPFS gateway port hardcoded to 8080

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#101]
If I change the IPFS gateway port from 8080 to something else, images and resources can't load any more. Starting Akasha in developer mode reveals that it tries (and fails) to connect to IPFS on port 8080, even though I changed it to 8079.

**Comment by kenshyx** [comment]
Can you check  in `"Addresses"` if `"Gateway"` is `"/ip4/127.0.0.1/tcp/8080"` from `~/.ipfs/config`? It should change to `"/ip4/127.0.0.1/tcp/8079"`.

**Comment by karalabe** [comment]
```
$ cat ~/.ipfs/config | grep Gateway
    "Gateway": "/ip4/127.0.0.1/tcp/8079"
```

![ipfs](https://i.imgur.com/RSUZJUS.png)

**Comment by kenshyx** [comment]
Refresh the page 2-3 times, it should work. We're gonna fix this for the next release :D
