### ISSUE TITLE
there is no button to retweet an entry

### ISSUE THREAD

**Issue by dirmansebastian** [AkashaProject/dapp#104]

**Comment by MihaiAlisie** [comment]
After long debates we decided that there's no need for a retweet button when the same functionality (propagating a message across the social graph) is fulfilled by the voting functionality. Compared to a simple retweet a vote carries with it additional info in the form of voting weights assigned by you (1 to 10).

So, when you are voting on an entry it will automatically show in the streams of the people following you and in the future release(s) on your profile page as well - just like a retweet but with additional information from your vote weight.
