### ISSUE TITLE
Following Feed

### ISSUE THREAD

**Issue by Kuurusch** [AkashaProject/dapp#106]
What exactly is meaned with following feed? I'm Following for example the user nationalgeografic. But under the column Following Feed there are not all entries of the user nationalgeographic. Why that? Did I missed something or is it a bug?
<img width="1083" alt="bildschirmfoto 2018-01-09 um 21 05 46" src="https://user-images.githubusercontent.com/11612401/34741198-1c7a23ee-f582-11e7-889b-3fd1c6096d2a.png">

**Comment by bogdanbrezuica** [comment]
Looks like a bug. Did you try to refresh the Following feed column?

**Comment by bogdanbrezuica** [comment]
Can you give more details about how you found this? For example, did you just follow nationalgeographic or you were following him for a while?

**Comment by dirmansebastian** [comment]
1. i see max 2 posts in dashboard for next columns: latest entries, following feed, user, tag
2. for list i see max 3
3. when i click an user it's same as point 1 (2 max)

**Comment by Kuurusch** [comment]
@bogdanbrezuica yes, I've tried to refresh, but no more entries were loaded.
I've just followed nationalgeographics, so no, I didn't followed him fore a while.

**Comment by bogdanbrezuica** [comment]
This should be fixed by now. Please re-open the issue if it's still there. Thanks!
