### ISSUE TITLE
When including foto and changing how to include photo -> white screen

### ISSUE THREAD

**Issue by Kuurusch** [AkashaProject/dapp#118]
The title describes the problem already. I've wrote an article (Human Connection) and postet it. Afterwards, I wanted to edit the article to include a photo. Till here, this worked. But then I've wanted to play with the buttons to change how to include the photo in the text, booom...

Now it is possible to read the article, but as soon as I trie to edit the article again -> white screen

I get now also a white screen, as soon as I cklick in the menue "Go to my drafts"

I use a MAC and version 0.6.1

**Comment by SeverS** [comment]
hello @Kuurusch. can you try to create a new article and add a picture to it? do you have a mac with retina display?

Thanks for reporting!

**Comment by Kuurusch** [comment]
hello @SeverS, ok I've did it and it ended also in a blanc window. I think just in the moment when the article was published. After restart of akasha I saw the article and I can open it to view.
Yes, I work with a Mac with retina display.

**Comment by Kuurusch** [comment]
I don't know if it is still the same bug, but I've tested it now in 0.6.2 and it seams, that it is still there. I've created an article and changed rigth after I loaded an image in the article the textflow-behaviour. And boom...
