### ISSUE TITLE
[0.6.1] Cannot create post with account

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#126]
I have a few accounts to test different stuff with, and my `spambot` account cannot currently make posts, as the UI gets borked. Not sure why this might happen as I can create posts with my other accounts:

![ui](https://i.imgur.com/JpgoOa4.png)

I tried posting the exact same entry from another account and there it works.

**Comment by karalabe** [comment]
I've opened Akasha in developer mode and there was no .js error reported, so it's not something blowing up loudly.

**Comment by bogdanbrezuica** [comment]
Duplicate of #119

**Comment by karalabe** [comment]
:+1:

**Comment by kenshyx** [comment]
This happens because of all your tokens are locked(manafied)

**Comment by karalabe** [comment]
@kenshyx Why do I need tokens to post? I didn't need them until now

**Comment by kenshyx** [comment]
Its just an UI issue, it shouldnt happen
