### ISSUE TITLE
Confirmation Manify windows behind Mana pull window

### ISSUE THREAD

**Issue by dimoon** [AkashaProject/dapp#137]
#### System information

AKASHA version: `0.6.1 `

Operating System: `windows `

#### Expected behaviour
Confirmation Manify windows should be visible

#### Actual behaviour
Increase Mana pull window hide Confirmation window at least on small resolution - picture attached
[http://www.zimagez.com/zimage/screenshot-01182018-084052pm.php](url)
#### Steps to reproduce the problem
Click Mana > Increase > Submit

**Comment by bogdanbrezuica** [comment]
hey @dimoon . what windows version and device are you using?

**Comment by dimoon** [comment]
windows server 2008 r2

**Comment by bogdanbrezuica** [comment]
Unfortunately, supporting windows server 2008 is not a priority at the moment. After we have a stable and mature app we will work on supporting multiple platforms and resolutions. Sorry for the inconvenience
