### ISSUE TITLE
Not loading the page after publishing a post.

### ISSUE THREAD

**Issue by AkashaTilo** [AkashaProject/dapp#139]
#### System information

AKASHA version: `0.6.1 `

Operating System: ` macOS Sierra`

#### Expected behaviour

Showing the page after pushing the publish button.

#### Actual behaviour

After I wrote something and uploaded an image into my first post in Akasha I pressed publish and it kept saying loading drafts for 20 minutes. After 20 minutes I clicked on dashboard and there I could see my published post.

#### Steps to reproduce the problem

It was my first post I tried to make. First I wrote something and after I uploaded the image and tried to publish but it asked me to make Mana so I did. After I pressed publish again and then the issue happened.
![screen shot 2018-01-18 at 19 48 29](https://user-images.githubusercontent.com/35579089/35124110-08959c8a-fc8c-11e7-9cc3-80697213917a.png)

**Comment by bogdanbrezuica** [comment]
This should be fixed now. Thanks for reporting!
