### ISSUE TITLE
Images not showing up in a users post.

### ISSUE THREAD

**Issue by AkashaTilo** [AkashaProject/dapp#140]
#### System information

AKASHA version: `0.6.1 `

Operating System: ` macOS Sierra`

#### Expected behaviour
Showing the images in his post.

#### Actual behaviour
I opened the post of user '@renej' in the Akasha Dapp and his two images aren't showing up.

#### Steps to reproduce the problem

Go to the post of @renej named 'The cryptomarkets 2019 and onward.' Scroll down till you see these two icons below>
📷
📷
 

![screen shot 2018-01-18 at 20 17 21](https://user-images.githubusercontent.com/35579089/35124593-c4a14be4-fc8d-11e7-9257-829dfa73a9f8.png)

**Comment by bogdanbrezuica** [comment]
hey @AkashaTilo . those are not pictures, just emoticons. thanks for reporting though, keep it up 👍
