### ISSUE TITLE
[0.6.1] Entry copyright not set to the one specified during posting

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#141]
If I edit my post to change the copyright on it, it is correctly updated. However if I explicitly set it to "All Rights Reserved" during the original post, it is not set, just defaults to "Some Rights Reserved".

**Comment by RMBLRX** [comment]
Same here, except that when I post with all rights reserved and edit it with all rights reserved still selected, it still defaults to _some rights reserved_.

Also, why doesn't Akasha use Creative Commons or other existing forms of licensing?

**Comment by RMBLRX** [comment]
Just noticed that if I set my license to *all rights reserved* by default in my settings, my post ends up displaying *cannot find license info* (or something like that, I've already changed it to *some rights* because of this).
