### ISSUE TITLE
Suggestion: Explanation dialog for different karma levels

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#142]
Currently I can see in my account, that I have Karma Level X, and 

```
At your current level you can:
Publish Entries, Vote, Comment, Create Tags
```

If would make the system much more "addictive" if you would also display that "If you reach level X+1, you can also do Y", or at least have a popup table that lists the different karma levels achievable and the "bonuses" at that level.

**Comment by MihaiAlisie** [comment]
Hey @karalabe, that's what we're planning to do - however we are still figuring out what the milestones/functionalities unlocked should be... If you have any ideas or suggestions we'd love to hear them 🎩

**Comment by bogdanbrezuica** [comment]
This will be part of a bigger re-design of the UX, so I will close this issue. Thanks!
