### ISSUE TITLE
Trying to delete character from caption deletes entire image and caption

### ISSUE THREAD

**Issue by bockp** [AkashaProject/dapp#143]
#### System information

AKASHA version: `0.6.1`

Operating System: `Mac OS X Yosemite `

#### Expected behaviour

When pressing backspace inside the caption of an image, the character before the cursor should be deleted.

#### Actual behaviour

When pressing backspace inside the caption of an image, the entire image and caption is deleted.

#### Steps to reproduce the problem

* Create article
* insert image
* write text in Caption space
* try to delete any part of the caption text.

**Comment by SeverS** [comment]
I cannot reproduce this issue on my mac...
Can you try to re-install AKASHA? Maybe something went wrong.
Do you use .dmg or .zip?

Thank you!

**Comment by bockp** [comment]
I used the .dmg
will try to see what happens if I re-install
