### ISSUE TITLE
AKASHA app crashes if holding Shift and entering a character in image caption

### ISSUE THREAD

**Issue by bockp** [AkashaProject/dapp#144]
#### System information

AKASHA version: `0.6.1 `

Operating System: `Mac OS X Yosemite `

#### Expected behaviour

When holding Shift and trying to enter a Capital letter as the first letter in an image caption, it should enter a capital letter.

#### Actual behaviour

When holding Shift and trying to enter a Capital letter as the first letter in an image caption, AKASHA's window turns permanently white, and remains frozen.
Manually closing the app and restarting becomes necessary.

#### Steps to reproduce the problem

1. create article
2. insert image
3. click in Caption area of image
4. hold down shift
5. try to insert any character.

**Comment by SeverS** [comment]
I can't reproduce this issue.
Can you tell which character did you tried to insert?
Maybe it's a combination of keys or something.
I'm interested in this issue :)

Thank you!

![screen shot 2018-01-21 at 9 08 12 am](https://user-images.githubusercontent.com/5903809/35191712-a9a886f0-fe8a-11e7-906b-194b0182ead9.png)

**Comment by bockp** [comment]
hmmm... The issue seems to have completely dissapeared now, I can enter any character in capital letters in the captions without any effect now.

Strange, as I tested 4-5 times, managing to freeze the app and turn the screen white, using 4-5 different combinations of SHIFT-letter as the first entry to a Caption, before I opened the issue...

The character's I'd tried at the time were A, C, E and a few others to test if it really seemed to be a bug too.

I'll never understand how some errors just vanish like that XS
