### ISSUE TITLE
When password-promt appears, background is not deactivated

### ISSUE THREAD

**Issue by Kuurusch** [AkashaProject/dapp#145]
#### System information

AKASHA version: ` 0.6.1`

Operating System: ` MAC OS 10.13.2`

#### Expected behaviour
When writing a comment under an article and akasha is already running for several hours, it apears the password-promt. I think, in this situation it should not be possible to past further text in the comment text-area.

#### Actual behaviour
When the password-promt apears, the background is grayed-out and its not possible to click on any elements in the akasha-window, but it is possible to paste text in the comment-area. I recognised it, because I wanted to past my password in the password-promt, but the password text-field was not focused and so it pasted the text in the comment-area.

#### Steps to reproduce the problem
1. Let run akasha until it is locked. 
2. Write a comment under an article and click publish-button.
3. Password-promt will apear
4. Past text in akasha and because last activ textarea was the comment-field, it will past the text there.

**Comment by SeverS** [comment]
Yep, good catch :)
It will be solved in the next release

Thanks!
