### ISSUE TITLE
Essence collect panel

### ISSUE THREAD

**Issue by SeverS** [AkashaProject/dapp#146]
#### System information

AKASHA version: `0.6.1`

Operating System: `MacOS`

#### Expected behaviour
Should be able to collect essence from collect essence panel for entry with title `Why should give me upvotes`

#### Actual behaviour
Cannot collect essence (collect button is disabled with the message `You can only collect essence if your vote is aligned....`)

![screen shot 2018-01-21 at 8 45 12 am](https://user-images.githubusercontent.com/5903809/35191608-3e2d6dac-fe88-11e7-864c-860a0584d9d9.png)

**Comment by maxizrin** [comment]
I'm Windows 8.1
I get this too, fairly often.
I go over posts I visited/posted to collect essence.
