### ISSUE TITLE
[0.6.1] UI hangs when IPFS content is being retrieved

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#148]
I can't exactly formulate when this happens, but I've seen it quite a few times already. When loading my previous drafts, I've seem on multiple occasions that Akasha just hangs for a long while. Just experienced another hang when I wanted to load a post, and the comments were still "blurred out" (I killed akasha after about 10 minutes of not responding). I don't really know where these originate from, but my guess is that some IPFS retrieval blocks the UI.

If you have a suggestion on how I might debug this, I'd gladly try (i.e. developer options or whatnot).

**Comment by bogdanbrezuica** [comment]
This may be fixed by now (at least we haven't ran into it) with all the changes in how drafts and entries/comments are loaded. Please re-open this issue if it's still there
