### ISSUE TITLE
[0.6.1] Audit log displays tx as failed, but etherscan reports success

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#149]
Etherscan: https://rinkeby.etherscan.io/tx/0x2a54051c146f263374e11d03df6fdc9c87252e4ca0d0ca78a525bc43e0a01fa6

Akasha UI:
![audit](https://i.imgur.com/U95JXvJ.png)

**Comment by bogdanbrezuica** [comment]
Hi @karalabe . I see this is an older transaction (initiated in the 0.6.0 version). This was a known issue that was fixed for 0.6.1, so please let me know if you find any 0.6.1 transaction in this state. thanks!

**Comment by karalabe** [comment]
Ok :) Will do if I see one.

**Comment by bogdanbrezuica** [comment]
This should be fixed by now. Thanks for reporting!
