### ISSUE TITLE
Issue trying to upvote: Error code EUE01

### ISSUE THREAD

**Issue by clarkjdj** [AkashaProject/dapp#157]
Issue trying to upvote:
Error code EUE01: An error occurred while upvoting Sunset on Boracay #2

#### System information

AKASHA version: Version 0.6.1 (0.6.1)

Operating System: OS X 10.13.2

#### Expected behaviour
Should be able to upvote. Have 854 mana / 810 essence / 910 karma / 50 AETH. Seem like I should be able to upvote.

#### Actual behaviour
Throws error, won't upvote.

**Comment by bogdanbrezuica** [comment]
Can you see the failed transactions in the transactions log?

**Comment by clarkjdj** [comment]
Where can I locate the log? I'll take a look.

**Comment by bogdanbrezuica** [comment]
in the upper right corner, next to the notifications icon

**Comment by clarkjdj** [comment]
It doesn't show my attempts in the log, so perhaps I was just not signed in or authenticated?

**Comment by bogdanbrezuica** [comment]
it is a possibility, but it's difficult to tell

**Comment by bogdanbrezuica** [comment]
This seemed to be an isolated issue. Please re-open this issue if you can reproduce it. Thanks!
