### ISSUE TITLE
Illegal Essence collected from essence popup panel

### ISSUE THREAD

**Issue by maxizrin** [AkashaProject/dapp#166]
#### System information

AKASHA version: `0.6.1 `

Operating System: `Windows 8.1 x64 `

#### Expected behaviour
I should not even see entries about essence I can not collect, because my votes were against the majority, in this case.

#### Actual behaviour
The button was active, I pressed it, and after a moment, and it said I collected the essence but nothing changed.
I refreshed the essence collection popup, the button was active again, the second attempt succeeded, and I collected 100 essence that I was not eligible to collect.

#### Steps to reproduce the problem
1. Vote against the majority on a post.
2. Wait until able to collect.
3. Change profile name (I don't know if this is required, it's just something I did)
4. Use the essence collection popup, not the button on the post (that one is disabled, as it should), to try and collect the essence.
5. Repeat step 3 as many times as possible, as fast as you are able.

### Extra:
As shown below, I was able to collect twice from the same post.
And the entry still shows up in the essence collection popup, but the button is now grayed out.
![image](https://user-images.githubusercontent.com/17175314/35488689-15f59d38-0495-11e8-8246-68ef19d37602.png)

**Comment by bogdanbrezuica** [comment]
Hello @maxizrin . This is a known issue, it was fixed and will be included in the next release. Thanks for reporting!
