### ISSUE TITLE
Recommendation: Notification about new article or comments by category

### ISSUE THREAD

**Issue by mobiledevgroup** [AkashaProject/dapp#167]
Hi, only to suggest a recommendation: it possible to make change to the tag color for the category that has new article,comments or new content. Or display on the dashboard. Thanks you for the effort and dedication to this important initiative.

**Comment by bogdanbrezuica** [comment]
hi @mobiledevgroup . at this moment, a blue circle will appear on the "reload" button in each column if there are new entries that can be loaded. is this what you mean?

![new entries](https://user-images.githubusercontent.com/13481438/35679842-28267710-0761-11e8-8d51-6b3eac26d0c8.PNG)
