### ISSUE TITLE
Stuck with 'No peers available' in all entries except mine 

### ISSUE THREAD

**Issue by alphanmoon** [AkashaProject/dapp#192]
#### System information

AKASHA version: ` AKASHA_0.6.2_amd64`

Operating System: ` Debian GNU/Linux 9 (stretch)`

#### Expected behaviour
Titles as well as other entries content must appear in boards columns.

#### Actual behaviour
Stuck with 'No peers available' in all entries fields except mine. New entries appear but with no content inside.
![screenshot_2018-02-05_09-08-47](https://user-images.githubusercontent.com/25549734/35809248-14363a5e-0a56-11e8-9498-99216178a682.png)

**Comment by kenshyx** [comment]
This looks like a firewall issue. You need to allow traffic on these ports https://github.com/ipfs/go-ipfs/blob/master/Dockerfile#L54

**Comment by alphanmoon** [comment]
Sure, I firstly enforced the port forwarding on my router (keeping in mind this procedure is already embedded in ipfs init routine, whatever) with zero effect and found out my ISP is messing around these ports. Now it runs. Thx for assistance!
