### ISSUE TITLE
Error code EUE01 when I try to publish a link

### ISSUE THREAD

**Issue by mobiledevgroup** [AkashaProject/dapp#202]
#### System information

AKASHA version: ` `

Operating System: ` `

**Comment by SeverS** [comment]
Hello @mobiledevgroup 
That error is from upvoting an entry.
Can you confirm that link publishing failed?

Thank you!

**Comment by mobiledevgroup** [comment]
Hello
I try again and the link publishing was success . I think the cause of the error was bad internet connection.
Thank and I acknowledge the great work team Akasha is doing.



Cordialmente
Alexander Casañas

________________________________
