### ISSUE TITLE
Image Caption can't be captioned

### ISSUE THREAD

**Issue by shujimoriwaki** [AkashaProject/dapp#218]
#### System information

AKASHA version: `0.6.2 `

Operating System: ` windows 10`

#### Expected behaviour
Can type captions in the caption area of an image

#### Actual behaviour
Entering any letter in the caption area immediately brings up a blank screen. I have to reload to go back to the draft I was writing.

#### Steps to reproduce the problem

In a new draft, upload an image.
In the caption area type a letter. 
A blank screen should result.
But I have seen other accounts with images with captions so it's not every body.

Thank you!

**Comment by laurentiusp** [comment]
same thing happened to me entering a caption after changing the image/text layout

first this:
<img width="683" alt="screen shot 2018-05-30 at 12 40 32" src="https://user-images.githubusercontent.com/22351953/40717050-4ff25c94-640b-11e8-9e83-ef6dd9972f24.png">
 
after reloading, restarting akasha and go back to edit, this appears
<img width="707" alt="screen shot 2018-05-30 at 13 15 48" src="https://user-images.githubusercontent.com/22351953/40717144-9f9abdd6-640b-11e8-8fbf-ce15c132de44.png">


```
TypeError: Cannot read property 'src' of undefined
    in t
    in n
    in blockComponent
    in div
    in t
    in t
    in figure
    in div
    in t
    in div
    in div
    in div
    in t
    in div
    in div
    in t
    in div
    in div
    in t
    in div
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in InjectIntl(t)
    in Connect(InjectIntl(t))
    in t
    in t
    in div
    in i
    in div
    in t
    in t
    in InjectIntl(t)
    in div
    in t
    in div
    in t
    in InjectIntl(t)
    in Connect(InjectIntl(t))
    in DragDropContext(Connect(InjectIntl(t)))
    in t
    in t
    in t
    in IntlProvider
    in y
    in Connect(y)
    in r
```
