### ISSUE TITLE
"TypeError: targetNode.scrollIntoViewIfNeeded is not a function" on webdapp

### ISSUE THREAD

**Issue by siddartha1492** [AkashaProject/dapp#236]
#### 
Processor- i5-4440
Ram- 8 GB
GPU- None
Hardisk- Seagate 1 TB
Browser- Firefox 59.0.2 (64-bit)

AKASHA version: ` 0.7.0`

Operating System: ` Windows 7 (64)`

#### Expected behaviour

Adding new lines, pressing enter or clicking on the empty screen should not show error.

#### Actual behaviour

While creating a new entry, after adding 1-2 lines, if I press enter or click on the screen, there is a small crash. After reloading, the change is reflected. If I have to write a long article, I just can't do that.

#### Steps to reproduce the problem

I am getting the error:
```
TypeError: targetNode.scrollIntoViewIfNeeded is not a function
    in EntryEditor
    in div
    in div
    in div
    in Col
    in div
    in Row
    in div
    in NewEntryPage
    in InjectIntl(NewEntryPage)
    in Connect(InjectIntl(NewEntryPage))
    in Route
    in Switch
    in div
    in PageContent
    in div
    in DataLoader
    in AppErrorBoundary
    in InjectIntl(AppErrorBoundary)
    in div
    in DataLoader
    in div
    in AppContainer
    in InjectIntl(AppContainer)
    in Connect(InjectIntl(AppContainer))
    in DragDropContext(Connect(InjectIntl(AppContainer)))
    in Route
    in Router
    in ConnectedRouter
    in IntlProvider
    in ConnectedIntlProvider
    in Connect(ConnectedIntlProvider)
    in Provider
```
In my case, this error only appears when creating new entry. All other options are working fine.
Edit: My profile in an Alpha imported profile and not a new profile.
**Update: This issue does not mirror on latest chrome version (x64). So I guess it is an issue with Firefox. maybe it is missing some extensions or so.**

**Comment by SeverS** [comment]
Hello @siddartha1492 !
Thank for reporting!
What browser do you use? I need to reproduce this.
Thanks!

**Comment by siddartha1492** [comment]
Hi SeverS
Thanks for taking up the issue. As mentioned above, browser is Firefox 59.0.2 (64-bit). It is the latest release.

**Comment by SeverS** [comment]
This issue is now solved!
