### ISSUE TITLE
Error code GSE01 when trying opening AKASHA mac app while Mist is syncing

### ISSUE THREAD

**Issue by 42piratas** [AkashaProject/dapp#246]
_From @42piratas on April 21, 2018 0:0_

_Reporting because it might be a bug. Please, close if duplicated or known or expected._

Steps to reproduce: 

1 - Open Mist
2 - While Mist is syncing, open AKASHA mac app.
3 - Error code GSE01 pops-up (screenshot). 100% reproducible.

![akasha_desktop_gse01](https://user-images.githubusercontent.com/18232600/39078142-98e1739c-44dd-11e8-95e3-8cfd0fa17161.png)

_Copied from original issue: AkashaProject/Alpha#164_

**Comment by kenshyx** [comment]
The Akasha app will always try to start(until v1.0) its own geth node that's why it launches with error(the default ports are already in used by mist). You can try to change port numbers when starting mist if you want to run both applications.
