### ISSUE TITLE
Bug in smartcontract which sends AETH. Many people get sent 1000 AETH multiples times.

### ISSUE THREAD

**Issue by AkashaTilo** [AkashaProject/dapp#256]
#### System information 

Mac OS

AKASHA version: `0.7.2 `

Operating System: ` OS Sierra`

#### Expected behaviour 

Send AETH just once

#### Actual behaviour 

Sent AETH multipletimesfor many accounts as you can see in tokenholders list

#### Steps to reproduce the problem 

Go to https://rinkeby.etherscan.io/token/0x398a7a69f3c59181a1ffe34bed11dcb5df863a8a?a=0x0865fce5d5f3587b99865895c94008ec261d59bb  and see that this guy got the most AETH of all sent to him about 45 times

**Comment by kenshyx** [comment]
This is not a bug at contract level, it was a guy who spammed the faucet url :)
