### ISSUE TITLE
TypeError: targetNode.scrollIntoViewIfNeeded is not a function

### ISSUE THREAD

**Issue by Soooooooooo** [AkashaProject/dapp#258]
#### System information

AKASHA version: ` web `

Operating System: ` windows10 64bit `

#### Steps to reproduce the problem

[bandicam 2018-05-06 16-37-20-293.zip](https://github.com/AkashaProject/dapp/files/1985888/bandicam.2018-05-06.16-37-20-293.zip)

![image](https://user-images.githubusercontent.com/25975648/39787484-88cd06ba-5360-11e8-85e8-08c5547a9b68.png)

**Comment by SeverS** [comment]
Hey @Soooooooooo, thanks for reporting.
This issue is now solved!
