### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by ChaceHunter** [AkashaProject/dapp#28]
When creating a `Link Entry`, the only time the link clicks through is when clicking on link in newsfeed.
Link doesn't work it is clicked in the actual post.

Links also do not work in regular posts.

No link appears when linking text

<img width="738" alt="screen shot 2017-12-22 at 6 52 29 pm" src="https://user-images.githubusercontent.com/12126485/34315698-4ac22fae-e749-11e7-8d07-f47be9af7373.png">

**Comment by MihaiAlisie** [comment]
![why meme](https://user-images.githubusercontent.com/6831213/34351937-4731130a-ea28-11e7-9e2d-c2acc85a28eb.png)
