### ISSUE TITLE
The akasha-app has no icon

### ISSUE THREAD

**Issue by Kuurusch** [AkashaProject/dapp#31]
Hallo, as the title already says, the app has no icon!
<img width="395" alt="bildschirmfoto 2017-12-23 um 12 02 36" src="https://user-images.githubusercontent.com/11612401/34319097-42b65e08-e7d9-11e7-9420-047130619ae3.png">

**Comment by lkngtn** [comment]
Can confirm I have the same issue.

**Comment by MihaiAlisie** [comment]
Hey @Kuurusch @lkngtn ,

Yep can confirm that the icon is missing on Mac. This happened because electron changed some of the paths to resources on build, only on Mac 😔 We will look into this more and try to fix it in the next release!

Thank you for your understanding! 🙇
