### ISSUE TITLE
Deleted drafts stay in List as drafts but with the title "No title"

### ISSUE THREAD

**Issue by Kuurusch** [AkashaProject/dapp#33]
Hey, it seams that deleted drafts don't disapears completly. Is this a bug or dit I missed something?

**Comment by MihaiAlisie** [comment]
Not sure 🤔. Can you send a screenshot?

**Comment by MihaiAlisie** [comment]
This issue is fixed in the 0.6.1 release! 

Thanks for reporting it! :bowtie:
