### ISSUE TITLE
If no Board exists, "add column" gives no error message

### ISSUE THREAD

**Issue by Kuurusch** [AkashaProject/dapp#34]
Hey, it would be good to give an error, when you klick on "add column" but there exists no board!

I've came over this problem, after I've restored my old account with no board. It was quite confusing.

**Comment by MihaiAlisie** [comment]
Good catch! We missed this one, but we'll fix it in the next release!

**Comment by bogdanbrezuica** [comment]
Fixed, thank you for reporting!

**Comment by MihaiAlisie** [comment]
This issue is fixed in the 0.6.1 release! 

Thanks for reporting it @Kuurusch ! :bowtie: 

<img width="1282" alt="screen shot 2018-01-17 at 3 23 37 pm" src="https://user-images.githubusercontent.com/6831213/35044893-a7fe053e-fb9a-11e7-8d43-ee4741d02ac2.png">
