### ISSUE TITLE
why is it not possible to add new categorie when editing an article?

### ISSUE THREAD

**Issue by Kuurusch** [AkashaProject/dapp#37]
Why?
Use akasha on mac

**Comment by MihaiAlisie** [comment]
Hey @Kuurusch,

We are barely getting started with this new iteration, so please be patient - we are figuring out things as we go 😅 At the moment tag changing after publishing can be easily abused by spammers, on the other hand, you should be able to edit the content without any problems ⛓ 

Cheers and Merry Christmas! 🎄 🎁 🎅
