### ISSUE TITLE
Clicking on this entry resulted in blank window

### ISSUE THREAD

**Issue by ChaceHunter** [AkashaProject/dapp#38]
I clicked on the following entry to view it, and this happened: 
![akashablankscreen](https://user-images.githubusercontent.com/12126485/34321906-3aed095a-e7df-11e7-81fc-d2bf4dab2dc4.gif)

Reloading the window did not fix the problem. Initially I thought it may be an issue with the imported account, but viewing his other entries resulted in zero problems.

This was the Mac version of Akasha. I will try to replicate with Windows, and will report in a comment if the same issue applies.

**Comment by ChaceHunter** [comment]
Confirming the problem exists on Windows as well.

**Comment by ChaceHunter** [comment]
So I just tried to click on another of his posts, and the issue does indeed occur. I'm wondering if it is because there just isn't any peers, and it is not getting reflected in the UI?

**Comment by Kuurusch** [comment]
No, as I wrote in  my issue, it happens also by me. (Im arminius)

**Comment by MihaiAlisie** [comment]
Interesting 🤔 

Thanks @ChaceHunter and @Kuurusch for reporting this! 🙇

**Comment by SeverS** [comment]
#36

**Comment by SeverS** [comment]
Got it! Fixed! Thanks @ChaceHunter and @Kuurusch for pointing this out!
