### ISSUE TITLE
Linux datadir path browse window froze

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#40]
I've no idea whether this is an Akasha issue or with my setup (I have fairly recently updated Ubuntu, though I haven't yet seen such error on my system). When going into the Advanced Settings on the startup screen, I tried to switch Geth's datadir from the default to some custom location. The first few invocations that I tried to open up the browse window, the window froze up. I could only close from the keyboard. At the 4-5th invocation mouse clicks started to work. I didn't have time to try and repro this, but figured an issue might be nice just in case others encounter it.

**Comment by kenshyx** [comment]
This is a known issue on Linux. The app does not freeze, it just glitches from the input file modal(native) so you cant make any selection using the cursor. The keyboard navigation works fine, you can press esc key to exit the modal.

**Comment by kenshyx** [comment]
Fixed in v0.6.1
