### ISSUE TITLE
Account listing doesn't notice key copies

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#41]
I already have an existing Rinkeby account. After syncing the chain (into a new folder), Akasha displayed a window to select existing accounts (none there yet) or to create one. I copied over my existing account into Geth's keystore, but I had to restart Akasha to notice it.

This is not a bug, rather a nicety. I'm not fully sure how best this could be implemented at your side to listen for account notifications from Geth, but it might be worth a discussion when you have the time to focus on niceties too :)

**Comment by kenshyx** [comment]
We can do something like a polling request for current accounts while displaying the login section.
