### ISSUE TITLE
Feature request: Show an audit log of transactions from Akasha

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#42]
Akasha sometimes creates transactions on user's behalf (e.g. register user). However there's no trace of the list of transactions Akasha made (at least not the register), so there's no easy way for the user to see what actually happened with that transaction. Is it sill pending, is it done, did it get lost? Perhaps a link to etherscan would also be valuable. Similarly perhaps linking your account to etherscan somewhere might be a good help to debug things.

**Comment by kenshyx** [comment]
Yep, we should provide a link to etherscan for every pending transaction.
