### ISSUE TITLE
Can't reshape cover photo

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#44]
A user rarely has a cover photo of the exact dimensions and cropping for an online service. Akasha currently just picks some random cropping and doesn't give the user the option to override or fix (slide the "view" on the uploaded image). This is imho quite an annoying thing. I know it's a low priority feature, but until then you could put a small placeholder label somewhere with the image dimensions or ratio you're looking for so users can crop offline.

**Comment by karalabe** [comment]
Further bug. When uploading a cover photo, the displayed image is **not** centered, whereas the image in the profile view **is** centered, so it's essentially a shoot and miss to configure a cover photo that looks correct.

**Comment by kenshyx** [comment]
@SeverS @quininez
