### ISSUE TITLE
Loading the profile of a user results in an "erroring" entry list

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#46]
> No peers available

![Imgur](https://i.imgur.com/88ZTJbU.png)

**Comment by karalabe** [comment]
Interesting that it works for other users. Perhaps Marius is offline and his content went with him? Or perhaps the contract references some non existing posts?

**Comment by kenshyx** [comment]
My content didn't have time to propagate to other users or pinners. The message 'no peers available' it's about the ipfs peers who can provide that content.
