### ISSUE TITLE
Cannot delete draft

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#47]
If I try to create a new post (tried posting a URL), and in the end decide not to do it and want to delete the draft, I get a popup asking for confirmation, but even after clicking yes, the `No Title` draft remains there in the list.

**Comment by kenshyx** [comment]
@SeverS

**Comment by SeverS** [comment]
#33

**Comment by MihaiAlisie** [comment]
This issue is fixed in the 0.6.1 release! 

Thanks for reporting it! :bowtie:
