### ISSUE TITLE
No AETH for existing accounts

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#48]
I've logged into akasha using my existing Rinkeby account, and I don't have any AETH, so I can't really interact with the platform at all. Is there a faucet to request AETH, or perhaps you forgot about this use case of people with pre-existing Rinkeby accounts?

**Comment by karalabe** [comment]
I've tried creating a new account, and there's a whole onboarding process that's skipped if I have existing accounts. This might be an interesting hiccup so I'd recommend sorting this out before the next batch of invites.

**Comment by kenshyx** [comment]
This is an issue from the UX perspective, right now you can go and edit your profile and you will receive tokens and aethers if you dont have any.

**Comment by karalabe** [comment]
But if I do have ETH, just no AETH?

**Comment by kenshyx** [comment]
Yep, its a bug. @SeverS

**Comment by MihaiAlisie** [comment]
Thanks for reporting this @karalabe !

In the 0.6.1 release, when no AETH is available, a modal allow the user to request AETH from the faucet! 💸
