### ISSUE TITLE
Cannot access drafts, only by creating and discarding a post

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#49]
If I have a post saved as a draft, and I want to go back to it later, there's no way to access the dratfs tab. The only way I found is to create a new temporary post, and then cancel it, which leaves me in the drafts view and allows me to access the original post I wanted to continue editing.

**Comment by kenshyx** [comment]
@SeverS

**Comment by MihaiAlisie** [comment]
Hey @karalabe thanks for the feedback! 

This issue is fixed in the 0.6.1 release, looking forward to hearing your thoughts!
