### ISSUE TITLE
Can't edit tags when editing a post

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#50]
After successfully creating a post, if I go into edit mode, I can expand on the text, change the title, etc; but I cannot edit the tags. All the tags do have little `x` marks, but they don't do anything; and also there's a `#category...` label which I assume could be used to add new tags, but that's disabled too.

**Comment by kenshyx** [comment]
This is a limitation from our contracts, you can't edit tags on posts right now because it will result into a too high complexity on the client when fetching events. We're working on it.

**Comment by karalabe** [comment]
That's fine, perhaps just change the UI a bit to reflect this.
