### ISSUE TITLE
Notification icon doesn't work? Or just not yet implemented?

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#52]
Beside the available ETH and AETH, there's a small notification bell. I'd expect that to list all my notifications from the platform (my post was submitted, my comment posted, my upvote registered, I got a tip from someone, etc). Not sure what it does as it doesn't work yet ;P, but please have a place listing an entire audit log of all the events.

**Comment by kenshyx** [comment]
It's not implemented :D

**Comment by bogdanbrezuica** [comment]
Now we have notifications 🎉
