### ISSUE TITLE
Essence view doesn't list from who it came from

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#56]
The essence view apparently should list who gave it to me, but it doesn't:

![Essence](https://i.imgur.com/FLbjskM.png)

**Comment by kenshyx** [comment]
Most probably is from voting an entry. This blank part happens because it can;t resolve the entry title.

**Comment by karalabe** [comment]
Another question regarding this. Shouldn't essence only be given after 24 hours? I did a post and I got this essence about 1h later.

**Comment by kenshyx** [comment]
You can get essence from comments also, which is instant

**Comment by karalabe** [comment]
Aaaa, I see. Thx!

**Comment by kenshyx** [comment]
But its a bug indeed :))

**Comment by karalabe** [comment]
There's a second similar issue. If I upvote a "link", not a post, then the title is again missing (maybe the post didn't specify one? still).

![NoTitleEssence](https://i.imgur.com/jnj6ZW6.jpg)

**Comment by bogdanbrezuica** [comment]
Thanks for reporting. Bugs fixed

**Comment by MihaiAlisie** [comment]
Seems like this bug has 🐛 morphed 🦋 ... 

On the bright side you can now see the title of the entries you can claim Essence from. On the "not so bright side" sometimes the collectable Essence amount displays 0 in the popover even if it's not 0 😥 

We'll keep hacking at it, it's one of the prioritized fixes for the 0.6.2 release.

Thank you for your understanding! 🙇
