### ISSUE TITLE
Make log limits a bit larger?

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#64]
As I see it, the logs in the `AKASHA/logs` folder are limited to 10KB. Perhaps you could bump those to something more meaningful, like 10MB? Just asking because 10KB is about 45 block import log lines in Geth, which isn't that useful to see what went wrong, if something goes wrong.

**Comment by MihaiAlisie** [comment]
The log limit is increased in the 0.6.1 release! 

Thanks for reporting this @karalabe ! :bowtie:
