### ISSUE TITLE
Converting essence into AETH always fails

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#66]
E.g. https://rinkeby.etherscan.io/tx/0x01d7f8d6977e595f8e1d013ac70285041b2386a2583751ee46fcd5fc0c7885df

**Comment by karalabe** [comment]
Apparently the transaction is calling `bondAETH` (`0x501951ed`) instead of consuming the essence. Perhaps the UI is calling a wrong method?

**Comment by karalabe** [comment]
Yes, definitely that's what's happening, as I can see failed "Manafy" attempts in my transaction history for the AETH token, even though I clicked "Forge AETH":

![Imgur](https://i.imgur.com/Rey3HAo.png)

Also an additional bugreport. After I do such a thing and the transaction fails, most of the Akasha UI goes belly up and I have to restart everything for it to revive.

**Comment by karalabe** [comment]
In `essence-popover.js`, line 92:

```js
        if (page === FORGE) {
            return (
              <ShiftForm
                balance={balance}
                onCancel={this.onCancel}
                onShift={this.onShiftUpSubmit}
                pendingShift={pendingTransformEssence}
                type="transformEssence"
              />
            );
        }
```

But the action here is `onShiftUpSubmit`, which is actually manafy:

```js
    onShiftUpSubmit = (amount) => {
        const { loggedEthAddress } = this.props;
        this.props.actionAdd(loggedEthAddress, actionTypes.bondAeth, { amount });
    };
```

**Comment by karalabe** [comment]
Ahahahahaaaa :smiling_imp: 

```
eth.sendTransaction({from: eth.accounts[0], to: "0xd8c6dd6d69ad4e37d6ea1b58b3ea9e06857c2550", data: "0x5302133200000000000000000000000000000000000000000000003860e639d806400000", gas: 100000});
```

https://rinkeby.etherscan.io/tx/0xb91c0dfb161d8cc8c055fba8fc1ddcfbff25800354cbf44ecd7047fa59ac0d9a

Next bugreport: The UI told me I should get 1.04 AETH for 1040 Essence, but I got 155.(5) from the contract.

**Comment by karalabe** [comment]
Perhaps an old version of the Essence contract was deployed? The `transformFactor` is `9` on the current system, not `1000` as it should be. And I can't see any transaction against the Essence contract that called `setFactor`.

**Comment by bogdanbrezuica** [comment]
Fixed the UI issue. Thanks for the (very) detailed issue :D
