### ISSUE TITLE
Left-side counters only update on profile reload

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#67]
If I collect some essence/karma, the sidebar icons don't get updated only after I load my profile view.

**Comment by bogdanbrezuica** [comment]
hey @karalabe . I found and fixed this issue only for the karma counter. When you have some time, can you confirm (or not) the issue was only with karma?

**Comment by karalabe** [comment]
Just tried collecting some Essence and that seems to update correctly, so probably only Karma.

**Comment by karalabe** [comment]
However if I have my profile page loaded, the essence counter on the profile page itself doesn't update.

**Comment by karalabe** [comment]
The `Essence total score` under the profile pic.

**Comment by karalabe** [comment]
Btw tried the mana counter too, and that also seems to update correctly on the sidebar.

**Comment by bogdanbrezuica** [comment]
> However if I have my profile page loaded, the essence counter on the profile page itself doesn't update.

Nice catch, thanks! Fixed this too
