### ISSUE TITLE
Akasha's Logo doesnt appears (Mac - OS X El Capitan version 10.11.6)

### ISSUE THREAD

**Issue by CarmenTanaka** [AkashaProject/dapp#68]
<img width="558" alt="captura de pantalla 2017-12-28 a las 19 04 27" src="https://user-images.githubusercontent.com/34898584/34419066-0655924e-ec02-11e7-9bcf-0d39314e55ef.png">

**Comment by MihaiAlisie** [comment]
Thank you for reporting this, the bug has been fixed in the 0.6.1 release! 😅
