### ISSUE TITLE
Only lowercase alphanumeric characters allowed

### ISSUE THREAD

**Issue by haadcode** [AkashaProject/dapp#73]
This is a small bug but getting a red warning/error is always scary as a first time user :) The error message persisted even though all the characters in the username are lowercase and alphanumeric. I was, however, able to create the account with the username, despite the error message.

<img width="1272" alt="screen shot 2017-12-26 at 11 35 37" src="https://user-images.githubusercontent.com/7499694/34480502-6e65413e-efb5-11e7-9c2f-eefafd37b36e.png">

**Comment by quininez** [comment]
I could not reproduce this bug, could you please provide additional info about how you got to that state?

**Comment by haadcode** [comment]
@quininez I believe I first entered "Haad" (uppercase H), got the error and then changed it to lowercase h. This was the very first time I opened the app afresh.

**Comment by MihaiAlisie** [comment]
Testing this issue from 0.6.1 but I cannot reproduce this bug either 🤔

@haadcode once we release the 0.6.1 (in a few hours from now) can you give it another try and see if the bug persisted?

**Comment by n13** [comment]
I have the same issue, brand new account / client download on OS X

I can't seem to set a user name at all, no matter what I try I get this error message.

![image](https://user-images.githubusercontent.com/65412/36259403-b015b930-1290-11e8-9fba-349be7e7cba6.png)

**Comment by n13** [comment]
Update: I got rid of this error by lower casing my first name, last name and about me.. not sure if that did it, but now it lets me sign up. Now I got an "you don't have enough ETH error" but that's a different story.
