### ISSUE TITLE
Confused about where to find content or users

### ISSUE THREAD

**Issue by haadcode** [AkashaProject/dapp#74]
After creating a profile and browsing through the different sections of the app, I found it confusing as to where the content and users are. There were some post "placeholders" but with no content. I found some users, but not many and generally it took time to find any content. It'd be great if the first time experience was guided or "pre-fed" in that there would be some content shown in the boards.

**Love** the dark theme btw! 😄 ❤️ 

<img width="1468" alt="screen shot 2018-01-01 at 10 15 23" src="https://user-images.githubusercontent.com/7499694/34480574-e142faa2-efb5-11e7-9c90-2841f689924e.png">

**Comment by karalabe** [comment]
Look me up `@karalabe` and for a nice photo stream `@nationalgeographic` ;) (yes, this was a blatant self advertisement :D :P)

**Comment by bogdanbrezuica** [comment]
Hello @haadcode . This looks weird, I will try to reproduce it. Have you tried to reload the window or restart Akasha?

**Comment by bogdanbrezuica** [comment]
This should be fixed now. Thanks for reporting!
