### ISSUE TITLE
Trouble Synchronizing It  

### ISSUE THREAD

**Issue by KelvinAndres** [AkashaProject/dapp#75]
The network stops synchronizing at the last second. It'll go all the way to 99 percent and stop. I'm on windows.

**Comment by bogdanbrezuica** [comment]
Hello @KelvinAndres . Have you tried to start Akasha again since then? It might have been a temporary issue.

**Comment by KelvinAndres** [comment]
Yes I did many times. I also deleted all Akasha files and reinstalled it. I synched it a total of five times literally all day and everytime I would get to the end it would just freeze.

**Comment by bogdanbrezuica** [comment]
Can you give more info please? Like:
- have you checked geth logs?
- are geth and ipfs running? (are the circles around the geth and ipfs icons green?)
- is the app frozen or it just doesn't load the next screen?
- what is the last message displayed below the synchronizing progress circle?

**Comment by KelvinAndres** [comment]
![akasha synch errors](https://user-images.githubusercontent.com/35050310/34611685-1b4db704-f1ec-11e7-9bf6-eb2d834b3b61.JPG)

**Comment by KelvinAndres** [comment]
![akasha synch errors 2](https://user-images.githubusercontent.com/35050310/34612173-2480b9f0-f1ee-11e7-9621-ccc0d6df87cf.JPG)

**Comment by bogdanbrezuica** [comment]
Thanks for the details. This is interesting, I'm not sure what is causing this, it seems to be related to geth. I have 2 suggestions you can try:
- search for "date and time settings" and make sure the "Set time automatically" toggle is on
![time settings](https://user-images.githubusercontent.com/13481438/34612854-2a983d2c-f234-11e7-86df-b2cb57069cc7.PNG)
- close Akasha, then delete the chaindata folder (default path is C:\Users\\%USER_NAME%\AppData\Roaming\Ethereum\rinkeby\geth\chaindata) and try again

**Comment by KelvinAndres** [comment]
By synchronizing the time I did manage to get it synch through the Fast Synch but not through the Express Regular Synch. I made my profile but now I have another problem. Everything is blank. I can't see posts from others. Should I still delete chaindata folder (default path is C:\Users\%USER_NAME%\AppData\Roaming\Ethereum\rinkeby\geth\chaindata)?

![blank akasha](https://user-images.githubusercontent.com/35050310/34616089-b1deb956-f1fc-11e7-9a17-8ae50ce141f9.JPG)

**Comment by bogdanbrezuica** [comment]
No, it's ok now. You just need to create a new board from the + button next to "My boards", and then add a column to see entries. In the next release we will have a placeholder that explains that you need to create a board first, so things will be more clear

**Comment by KelvinAndres** [comment]
Got it. Thank you for helping me in a timely manner I really appreciate it. Good luck on this project I'm very excited to see how far this will go.

**Comment by bogdanbrezuica** [comment]
Thanks :) Have fun!
