### ISSUE TITLE
Windows: No ESSENCE generated from multiple artifacts given a 10 Score

### ISSUE THREAD

**Issue by ChaceHunter** [AkashaProject/dapp#8]
I spammed 9 artifacts with @sebastianrs95 giving each of them 10 points to try and level up my KARMA, but I received 0 ESSENCE total.

This could be an anti-spam feature I'm unaware of though. :)

**Comment by bogdanbrezuica** [comment]
@ChaceHunter @sebastianrs95  have you reproduced this issue since then?
